---
title: "Quarto Practice"
format: html
execute: 
  warning: false
---

Suppressing warnings and messages JUST for this code chunk.

```{r}
#| warning: false
#| message: false
library(tidyverse)
```

Running code but not showing code or output.

```{r}
#| include: false
# return the first 6 lines of star wars data
head(starwars)

# return dimension of star wars data 
dim(starwars)
```

Showing output, but not code.

```{r}
#| warning: false
#| echo: false
# echo makes it so that you dont show output or code, but it does still run it

ggplot(data = starwars, aes(x = height, y = mass, color = mass)) +
  geom_point() + 
  labs(x = "Height (cm)", 
       y = "Mass (kg)")
```

Show only code and output.

```{r}
#| warning: false
#| fig-cap: "caption text"
#| fig-alt: "figure alt text"
#
ggplot(data = starwars, aes(x = height)) + 
  geom_histogram(color = "red", fill = "purple") 
```

Find summary stats for star wars characters.

```{r}
sw_height_mean <- mean(starwars$height, na.rm = TRUE)
sw_height_median <- median(starwars$height, na.rm = TRUE)
sw_height_var <- var(starwars$height, na.rm = TRUE)
sw_height_sd <- sd(starwars$height, na.rm = TRUE)

```

The mean height of the characters in Star Wars is `r round(sw_height_mean, 1)` centimeters.

```{r}

```

